/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:bb86d331-fc50-4ac4-8933-b03c2437e83d",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_df20bVY5Z",
    "aws_user_pools_web_client_id": "2im1fqc0lq2c9ltf21t41plegk",
    "oauth": {
        "domain": "login-dev.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://cloud.geniusrise.com/,https://cloud.geniusrise.com/,https://cloud.geniusrise.ai/,https://cloud.geniusrise.health/,https://cloud.geniusrise.com/,https://geniusrise.com/",
        "redirectSignOut": "https://geniusrise.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "FAMILY_NAME",
        "GIVEN_NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://jyajlj4v7f.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        }
    ]
};


export default awsmobile;
